#
#This is the list of all the VLANs that will be defined on Nexus, UCS and OCP
#
# Commenting out the following two variables will skip the iSCSI and/or FC configurations
configure_iscsi: "yes"
#configure_fc: "yes"
configure_nfs: "yes"
#
# Uncomment and update the the following lines to setup NTP Server(s)
ntp_servers:
  - ip_address: "192.168.156.21"
  - ip_address: "192.168.156.22"
#
# Uncomment and update the the following lines to setup DNS Server(s)
dns_servers:
  - ip_address: "10.1.156.250"
  - ip_address: "10.1.156.251"

# Uncomment and update the the following line to setup Timezone
time_zone: 'America/New_York'

# VLAN Names are adjustable and can be modified in here
#
native_vlan_name: 'Native-Vlan' # Native VLAN
oob_vlan_name: 'OOB-MGMT' # Out of Band Mgmt VLAN
baremetal_vlan_name: 'OCP-Baremetal' # Baremetal Management VLAN
provisioning_vlan_name: 'OCP-Provisioning' # VLAN to carry provisioning traffic
vm_traffic_vlan_name: 'OCP-VM-Traffic' # VLAN for VM management interfaces
persistent_nfs_vlan_name: 'OCP-Persistent-NFS' # NFS Traffic between OCP and Storage for Persistent Storage
iscsiA_vlan_name: 'OCP-Persistent-iSCSI-A' # iSCSI-A VLAN for Persistent Storage 
iscsiB_vlan_name: 'OCP-Persistent-iSCSI-B' # iSCSI-B VLAN for Persistent Storage
# lan_state should be set to 'present' to configure the objects
# In future, this parameter will be used for deleting the configuration
#
lan_state : 'present'
#
vlan_list:
  - name: "{{ native_vlan_name }}"
    id: '2'
    native: 'yes'
    state: "{{lan_state}}"
  - name: "{{ oob_vlan_name }}"
    id: '13'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ baremetal_vlan_name }}"
    id: '113'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ provisioning_vlan_name }}"
    id: '904'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vm_traffic_vlan_name }}"
    id: '914'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ persistent_nfs_vlan_name }}"
    id: '3154'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ iscsiA_vlan_name }}"
    id: '3014'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ iscsiB_vlan_name }}"
    id: '3024'
    native: 'no'
    state: "{{lan_state}}"
#
# VLANs definition below will be used to setup trunk ports on Nexus Switches
# all_vlans_list: for vpc_peer_link and UCS FI trunk ports
all_vlans_list: "13,113,904,914,3154,3014,3024"
# storage_vlans_list: for storage ports
storage_vlans_list: "113,3014,3024,3154"
# mgmt_vlans_list: for management switch trunk port
mgmt_vlans_list: "13,113"
#
native_vlan_id: "2"
#
