---
  # This Task Configures appropriate Timezone in UCS
  #
  - name: Configure Time Zone
    ucs_timezone:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      state: present
      admin_state: enabled
      timezone: "{{time_zone}}"
      description: 'Time Zone for US East'
    when: time_zone is defined
